services:
  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: hometown_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hometown_on
      MYSQL_USER: hometown_user
      MYSQL_PASSWORD: hometown_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DummyDB:/docker-entrypoint-initdb.d
    networks:
      - hometown_network

  # FastAPI 백엔드
  backend:
    build:
      context: ./HometownON/backend
      dockerfile: Dockerfile
    container_name: hometown_backend
    restart: always
    env_file:
      - ./.env # 루트의 .env 파일을 사용
    ports:
      - "8000:8000"
    volumes:
      - ./HometownON/backend/app:/usr/src/app/app # 코드 변경 시 자동 리로드
    depends_on:
      - db
    networks:
      - hometown_network
    # uvicorn으로 앱을 실행하고, 코드 변경 시 자동으로 리로드합니다.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Native 프론트엔드 (Metro 번들러)
  frontend:
    build:
      context: ./HometownON/frontend
      dockerfile: Dockerfile
    container_name: hometown_frontend
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./HometownON/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    networks:
      - hometown_network
    depends_on:
      - backend

  # Nginx (프록시 서버)
  nginx:
    image: nginx:alpine
    container_name: hometown_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - hometown_network

volumes:
  mysql_data:
  static_volume:

networks:
  hometown_network:
    driver: bridge
