INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (1, 1, 'Nulla qui at officia amet perferendis voluptate velit.', 'Voluptatem veritatis corporis praesentium magnam magnam assumenda. Adipisci culpa in. Dignissimos repudiandae aliquid.', '2022-04-04 13:15:13', '2024-03-07 05:07:38');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (1, 2, 'Ullam consequatur minus omnis perspiciatis fugiat harum similique deleniti perferendis.', 'Quasi id ea. Possimus earum minus dignissimos unde quis.
Quos ab autem aliquid adipisci nisi sunt. Totam recusandae reiciendis aperiam asperiores impedit accusamus.', '2025-04-17 16:56:52', '2025-06-05 09:49:03');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (1, 3, 'Delectus quo fugit mollitia non velit vero necessitatibus.', 'Accusamus sunt ducimus incidunt. Commodi mollitia architecto qui suscipit cumque.
Ipsum a similique labore tenetur consequatur. Minima eius optio.', '2020-07-20 21:14:37', '2022-01-06 10:36:31');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (2, 1, 'Est adipisci voluptas non.', 'At perferendis ut. Occaecati numquam voluptatum ad et iure pariatur. Debitis ratione culpa nam veniam omnis maxime ab.', '2023-11-26 09:36:26', '2024-06-01 07:46:42');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (2, 2, 'Expedita omnis consequatur ex necessitatibus nam.', 'Dolores inventore voluptatum quam sed eaque nulla quisquam. Beatae fugiat laboriosam dolores deserunt sapiente aliquam voluptate. Ex assumenda labore ratione at.', '2020-01-20 08:25:31', '2024-01-24 23:53:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (2, 3, 'Dolore minus quo sunt odio molestiae.', 'Explicabo aperiam minima nostrum illo. Iure odio expedita iste ab aliquid. Ad incidunt consequatur aperiam ipsa sed.
Ea vitae qui odio minima voluptatibus.', '2021-10-30 05:49:42', '2024-01-16 15:32:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (2, 4, 'Officia necessitatibus magni adipisci unde et.', 'Ab cupiditate repudiandae eum dignissimos. Eveniet numquam quas. Illum optio perferendis eaque. Doloribus iusto quasi minus.', '2020-05-11 13:52:57', '2020-09-23 00:27:18');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (3, 1, 'Consequuntur fuga assumenda quas quo incidunt eum laudantium.', 'Minus doloribus veritatis expedita ut. Deleniti iusto corporis minus deleniti esse nulla ad.
Quisquam laborum vel fugiat illo quaerat quae. Ipsa asperiores aut fugiat. Nisi aliquam culpa perferendis.', '2021-03-04 22:28:53', '2025-04-05 21:31:49');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (3, 2, 'Veritatis rem corrupti quis quaerat voluptate qui.', 'Fugit dolorum possimus temporibus assumenda impedit officiis quidem. Tempora tenetur aliquam maxime veritatis optio.', '2021-03-26 09:13:10', '2023-04-07 00:41:30');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (3, 3, 'Repellat est molestiae quos culpa odio corrupti aperiam numquam libero.', 'Eius minima culpa error nobis consequuntur totam. Ab minima quia voluptas iste a. Debitis esse voluptatum ex quasi.', '2022-02-04 11:20:49', '2023-02-22 14:51:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (3, 4, 'Aut porro sapiente illo quod totam assumenda facere voluptatibus esse.', 'Asperiores quam facere quia. Dolorum molestiae doloremque quo dolore ipsa sapiente vel.', '2024-04-21 05:34:06', '2025-03-12 04:24:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (3, 5, 'Delectus non similique ducimus accusamus ut enim nulla quibusdam.', 'Odit unde debitis. Quo qui quae corrupti. Corrupti aperiam ea expedita eaque libero possimus.', '2023-02-02 13:12:07', '2024-10-21 09:40:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (4, 1, 'Ut corrupti ea alias debitis aut magnam ipsa magnam at.', 'Tempora eligendi sint itaque nisi cumque commodi. Earum ratione aut quibusdam mollitia. Eum animi explicabo reiciendis placeat assumenda.', '2022-02-13 01:01:59', '2024-05-21 01:00:32');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (4, 2, 'Hic nihil voluptatem necessitatibus doloremque ab ipsum sit suscipit explicabo nobis.', 'Error quam accusantium sapiente vel. Tempora magnam libero quis ad ex.
Similique quas quae labore perspiciatis veritatis. Aliquid numquam architecto ipsam voluptatibus quos tenetur.', '2022-02-23 17:46:34', '2025-03-25 16:26:32');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (4, 3, 'Quaerat vitae inventore cumque ratione consequuntur facilis consectetur officiis.', 'Vel animi distinctio dolor aspernatur mollitia itaque. Hic in laudantium harum illo. Dolorum ut quo quibusdam numquam.
Ipsam quis culpa voluptatibus optio id cumque.', '2024-09-05 11:39:42', '2024-12-12 22:41:05');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (4, 4, 'Fugit quam recusandae eligendi aliquid culpa.', 'Corrupti praesentium dolore sequi. Eaque nostrum tempore fugiat deserunt libero.
Debitis ipsa fugiat quo excepturi maxime laboriosam. Odio maxime aliquam aperiam assumenda.', '2021-04-10 09:47:26', '2024-03-12 17:23:36');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (4, 5, 'Rem impedit et dolorum perferendis assumenda explicabo veniam.', 'Deserunt alias nemo minima blanditiis. Eveniet ex quas magnam.
Eveniet corporis velit aut. Cumque dolorum eligendi quod molestiae explicabo.', '2022-10-05 22:51:15', '2025-04-14 07:29:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (5, 1, 'Adipisci quo debitis sit hic facere vero quibusdam expedita.', 'Accusamus incidunt pariatur. Repellendus necessitatibus doloribus maxime.', '2023-02-06 06:55:36', '2024-08-16 01:42:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (5, 2, 'Quidem delectus optio dolor tenetur numquam hic asperiores.', 'Debitis ducimus consequuntur adipisci. Tempore doloribus dolorum maxime iusto ratione consequatur. Dicta autem ab in tempora distinctio ad.', '2024-02-12 04:16:52', '2024-05-06 00:50:46');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (5, 3, 'Suscipit veritatis cumque corrupti vitae.', 'Repudiandae quis laudantium architecto nesciunt. Placeat natus minus quia ipsum vero beatae.
Adipisci non esse ad ipsam eaque omnis. Aut amet provident consequatur corrupti excepturi commodi.', '2022-09-02 04:54:04', '2024-12-30 06:51:16');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (6, 1, 'Voluptatibus illo molestias minus numquam.', 'Delectus esse molestiae reprehenderit est iusto. Rem eum aliquam nisi. Soluta reprehenderit ipsam laboriosam esse quod fugiat.', '2024-07-08 00:38:35', '2024-12-06 14:54:39');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (6, 2, 'Id eum delectus distinctio voluptate.', 'Placeat ipsam accusamus sapiente suscipit eius eligendi voluptate. Corrupti perspiciatis quod est error laboriosam. Cumque similique expedita suscipit harum maiores quo.', '2021-09-26 14:14:39', '2023-01-05 14:05:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (6, 3, 'A quod illo iusto voluptatibus deleniti quasi nisi.', 'Facilis natus rem architecto labore quae vitae delectus. Exercitationem ducimus doloribus nisi placeat.
Laudantium beatae eveniet odit. Porro minus accusamus eos soluta iusto repudiandae.', '2023-07-17 01:39:02', '2023-08-01 20:14:24');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (6, 4, 'Aliquam magni suscipit perferendis corporis id saepe.', 'Esse quia consectetur sapiente hic distinctio molestiae a. Sit accusamus minima amet nemo eaque nemo.', '2020-08-10 04:02:24', '2022-04-27 04:25:34');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (7, 1, 'In omnis placeat excepturi blanditiis accusantium iste sit est.', 'Sed magni dolor illum.
Perferendis quam at officia.', '2025-06-03 04:08:58', '2025-06-17 00:18:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (7, 2, 'Debitis doloremque officia excepturi architecto at officia architecto ratione dicta.', 'Amet voluptates natus nam officiis ducimus. Est odio quo repellendus blanditiis quaerat quisquam. Veniam quis quibusdam voluptatum accusamus laudantium.
Eos nostrum cum minus tempora dicta ea.', '2025-02-18 23:49:51', '2025-03-17 05:38:57');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (8, 1, 'Incidunt delectus est fugit illum pariatur unde aut.', 'Nobis dolore hic sunt. Accusamus alias ab quo delectus ducimus.', '2020-11-10 20:28:28', '2024-12-24 23:52:14');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (8, 2, 'Ipsa officia laudantium perspiciatis commodi.', 'Impedit eligendi nam dolores dolorum. Hic ratione et earum. Facere et tenetur nulla quasi qui occaecati.
Odio veniam sit. Necessitatibus numquam earum sequi. Corporis saepe soluta.', '2022-10-03 07:21:22', '2023-04-27 08:19:38');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (8, 3, 'Maxime facilis perspiciatis magni suscipit corporis enim reprehenderit.', 'Quibusdam nesciunt sunt ullam a quas eum at. Iste ipsum ipsa praesentium tempore dolorum asperiores.', '2023-04-15 04:53:56', '2023-10-15 16:26:01');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (8, 4, 'Vel tenetur magnam magni hic reiciendis omnis.', 'Amet repellendus quia reprehenderit. Cumque excepturi officiis officia. Deleniti qui minima libero eum culpa quasi.', '2024-03-30 14:00:30', '2025-04-16 18:34:28');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (8, 5, 'Doloribus officiis sint ex nihil.', 'Quaerat vitae nisi ullam adipisci dolores. Perspiciatis quas eaque ad quaerat.
Ipsum hic tempore laudantium accusantium nostrum veniam. Voluptas qui nam commodi ex eligendi.', '2020-06-13 01:31:47', '2023-07-09 12:12:18');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (9, 1, 'Tenetur saepe quam dicta rem eius ipsa quod.', 'Molestias ratione facilis repellat. Laborum ipsum magni odio atque pariatur mollitia.', '2023-06-23 08:32:52', '2024-02-27 14:24:28');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (9, 2, 'Eius exercitationem eum ducimus molestias hic asperiores.', 'Commodi ex est officia aliquid. Distinctio eos necessitatibus fuga eaque nulla cum.
Autem consequuntur at aliquam harum quia assumenda. Distinctio quibusdam nulla deleniti.', '2021-01-15 10:36:54', '2022-01-04 14:51:50');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (9, 3, 'Doloremque soluta accusamus dolor enim esse vel quos laboriosam facilis fugiat.', 'Explicabo vero sint unde dicta molestias odit. Minus minus consectetur cupiditate ad ad placeat rerum. Quasi fugit quia repellendus recusandae.', '2024-08-30 06:13:26', '2025-02-01 10:58:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (10, 1, 'Accusamus nobis nulla dolor eligendi minima laudantium consectetur exercitationem eius.', 'Nesciunt in cum magni laborum.
Id accusantium labore optio. Nemo non consequuntur consequatur quia omnis quam. Quos enim rerum ex magni.', '2020-11-05 05:42:50', '2021-06-14 01:57:24');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (10, 2, 'Illum numquam maiores iusto quisquam nam non illum natus repellat.', 'Illum est dolorem nobis. Expedita nulla quasi natus repellendus ducimus deserunt fuga. Nesciunt provident consequuntur laborum. Dolorum accusantium voluptas eos corrupti.', '2025-03-25 02:12:17', '2025-04-25 10:15:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (10, 3, 'Minima excepturi error voluptatum maiores dolorem.', 'Sed veniam sequi debitis laboriosam distinctio. Veritatis natus doloribus accusamus facilis doloribus adipisci.', '2021-07-11 16:16:32', '2022-10-18 12:46:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (10, 4, 'Voluptatem neque aliquid expedita aspernatur maiores assumenda asperiores vel saepe sed.', 'Aspernatur impedit quia deleniti placeat natus. Laboriosam architecto molestias eaque eligendi.
Distinctio exercitationem natus. Repellendus expedita veritatis nobis laborum quia. Quidem qui ut modi.', '2024-11-12 10:04:49', '2025-05-15 03:13:24');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (11, 1, 'Exercitationem beatae suscipit perferendis fugit dolor consectetur.', 'Nihil suscipit nam porro et delectus. Temporibus cum officiis sapiente.
Quod iusto quibusdam animi accusantium nobis.', '2022-03-31 16:42:34', '2024-12-02 19:49:35');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (11, 2, 'Velit qui ex maiores blanditiis ipsum.', 'Fugit excepturi voluptatem magnam consectetur dolore. Repellendus cupiditate placeat eligendi.
Repellat aperiam enim quasi. At id dolore possimus ullam ut nihil fugit.', '2023-01-31 07:29:47', '2024-08-30 20:16:49');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (12, 1, 'Iusto odit dolorem quasi nam corrupti.', 'Ipsum sequi veniam dolorum doloribus ad. Voluptas voluptate laboriosam omnis provident excepturi.', '2020-09-05 07:01:13', '2023-04-06 11:59:40');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (12, 2, 'Dolores dolor cumque ut soluta quae error.', 'Fuga quia cupiditate consequatur excepturi saepe. Pariatur ad reprehenderit aperiam. Sunt quasi corrupti ducimus voluptatibus porro repudiandae non.', '2022-08-18 01:45:33', '2025-02-05 04:56:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (12, 3, 'Nesciunt itaque nobis vero nulla.', 'Provident tempora molestias impedit. Culpa aliquid aspernatur ullam aliquid minus. Deleniti nihil aliquam consequatur.
Officiis asperiores fuga nam illum adipisci.', '2020-12-22 13:46:40', '2021-06-20 09:47:17');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (13, 1, 'Aut autem consectetur animi amet sequi ipsum.', 'Adipisci esse at nobis distinctio impedit. Quo quibusdam facere dolorem delectus hic dolores beatae. Error dicta recusandae labore. Explicabo adipisci incidunt optio eligendi sed.', '2021-06-30 12:47:03', '2023-10-12 21:56:54');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (13, 2, 'Culpa esse ratione reprehenderit expedita minus quaerat.', 'Placeat quidem neque velit. Porro fugit earum labore.
Incidunt quia est vel voluptatibus incidunt repudiandae laudantium. Provident nulla perferendis nulla.', '2021-05-19 10:02:55', '2023-12-19 20:07:38');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (13, 3, 'Voluptatum voluptates omnis doloremque esse aliquam cum fuga unde illum.', 'Quo a cupiditate recusandae occaecati libero perferendis nemo.
Minima earum corrupti. Quae maiores delectus autem. Qui minima eaque nemo nulla cumque ducimus accusantium.', '2024-08-28 11:28:00', '2024-09-25 00:12:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (13, 4, 'Optio id reprehenderit corrupti pariatur illum laborum.', 'Dolor dolores assumenda occaecati harum illo. Eum tempore molestias fuga.
Nulla quos pariatur dignissimos libero quo. Adipisci minus laborum dicta fuga maiores. Incidunt molestiae nostrum officiis.', '2022-08-02 21:48:05', '2024-02-21 18:25:34');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (14, 1, 'Earum reiciendis amet temporibus illum cumque magnam blanditiis.', 'Iure dignissimos alias iure. Voluptas ea itaque suscipit quae deleniti iste.', '2025-05-10 20:21:59', '2025-06-06 20:52:21');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (14, 2, 'Officia optio veniam optio similique cum voluptatibus tenetur rem tempore.', 'Voluptatibus molestiae a beatae. Aut temporibus assumenda cupiditate soluta sint officia. At aut adipisci eveniet.', '2022-11-06 13:48:09', '2024-08-11 08:49:19');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (14, 3, 'Alias saepe nostrum explicabo commodi totam amet.', 'Dolor expedita perspiciatis blanditiis temporibus libero quis. Hic magni delectus soluta. Consectetur est ullam perferendis.', '2020-01-13 13:00:48', '2023-12-31 16:20:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (15, 1, 'Repellendus eum eos voluptatibus officia magnam cumque veritatis atque.', 'In nemo excepturi pariatur. Commodi quas nulla doloribus in voluptatibus eligendi. Fugiat quibusdam non nisi dolor. Sapiente quidem veniam pariatur reprehenderit.', '2020-06-03 21:23:45', '2023-08-06 17:16:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (15, 2, 'Quos quibusdam at occaecati magni.', 'Doloremque mollitia totam vero quos sapiente. Modi quia ipsa quod. Magni assumenda qui quos odio rerum.', '2022-05-25 02:24:46', '2024-02-17 17:22:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (15, 3, 'Corrupti rem voluptatem praesentium eveniet fugit nulla laudantium earum.', 'Maiores voluptatum dolores asperiores eum molestiae. Rerum beatae nobis.', '2023-04-20 10:23:41', '2024-09-22 00:06:42');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (15, 4, 'Placeat repellat ipsam repudiandae nostrum provident odio excepturi quia possimus.', 'Laudantium libero optio. Reiciendis sunt corporis sed nulla iste. Odit vel cupiditate expedita beatae cumque iusto.', '2021-11-28 21:24:05', '2024-06-05 18:47:47');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (16, 1, 'Hic autem odit quo sint labore deserunt.', 'Consectetur quae quos asperiores. Quaerat ipsam quam perferendis assumenda rem similique.', '2023-12-14 20:03:14', '2024-05-14 23:16:53');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (16, 2, 'Ipsum libero dolorum est sint temporibus iure.', 'Fuga alias error incidunt soluta asperiores aliquid. Ea laborum at eius necessitatibus aliquid.', '2022-01-23 00:35:31', '2023-10-14 23:33:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (16, 3, 'Alias esse voluptas magni soluta reprehenderit minus.', 'Eos sequi ex. Aliquid similique beatae neque corrupti. Explicabo facilis quia saepe officiis culpa nihil.', '2023-01-04 05:37:04', '2024-01-01 00:41:21');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (16, 4, 'Ipsa porro voluptatum impedit fuga aperiam sint commodi.', 'Possimus culpa inventore dolores minus labore in incidunt. Quisquam earum eum tempore corrupti perspiciatis modi. Tempore quod quasi voluptas.', '2021-07-08 22:53:27', '2023-12-02 06:10:56');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (17, 1, 'Autem ipsa porro dolorum repellat natus dolores tempora sequi commodi.', 'Consectetur eveniet blanditiis officia ad. Illum esse explicabo cupiditate officiis impedit veniam quod. Et officia quod modi occaecati aliquam assumenda odio.', '2020-11-17 10:23:41', '2021-05-09 20:04:43');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (17, 2, 'Praesentium et ea quas nam.', 'Nesciunt officiis alias mollitia error. Esse reprehenderit numquam commodi nostrum asperiores nesciunt molestiae.', '2020-11-28 06:26:34', '2022-10-04 11:44:47');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (18, 1, 'Enim non qui eligendi esse cumque suscipit aliquid facilis.', 'Dolorum eveniet nesciunt sequi.
Nesciunt dolorem aliquid possimus ex praesentium dignissimos. Natus eum a quam esse quia expedita provident.', '2023-06-30 00:42:22', '2024-09-22 07:25:18');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (18, 2, 'Autem suscipit et molestiae veniam.', 'Officia qui non. Laboriosam amet similique amet iusto.', '2020-06-13 13:27:22', '2025-02-27 08:51:03');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (18, 3, 'Et esse aliquid deleniti in eius.', 'Voluptas odio possimus quia laboriosam. Doloribus magni placeat corrupti itaque corrupti.', '2024-04-09 00:21:48', '2025-04-15 13:05:36');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (19, 1, 'Quaerat occaecati quia vel voluptatum ut non recusandae quibusdam qui.', 'Odio facilis molestiae est autem delectus quidem veniam. Maxime incidunt eligendi corporis animi velit.
Iure quo qui itaque ratione eaque eveniet vel. Dolores omnis delectus ab neque.', '2020-10-19 14:40:02', '2025-05-21 05:12:01');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (19, 2, 'Velit dicta officiis repellendus neque cupiditate.', 'Optio debitis fugit deleniti ex a. Impedit neque placeat perspiciatis perspiciatis.
Tenetur eaque inventore. Cupiditate corporis excepturi velit iure. Vitae dolorem vitae cumque accusantium.', '2022-03-18 05:51:53', '2023-03-23 08:27:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (19, 3, 'Alias vero voluptatum placeat commodi dignissimos hic itaque culpa delectus.', 'Maxime impedit ut dolor. Vel doloribus sed occaecati hic. Ex voluptate sequi corporis labore quibusdam neque.', '2020-08-18 05:13:14', '2024-10-06 07:55:24');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (20, 1, 'Repudiandae excepturi consequuntur nulla.', 'Deleniti maiores id quam blanditiis explicabo. Est architecto assumenda harum nihil tempora. Nam fugit autem recusandae commodi animi. Velit eaque fugit sed.', '2021-12-30 22:14:29', '2025-03-02 15:36:17');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (20, 2, 'Nihil ut aperiam temporibus nulla nihil id quae.', 'Eos animi rerum ab. Accusantium eum quis nulla corrupti dolorem sequi. Expedita voluptate maxime qui rerum nostrum.
Consectetur sit impedit omnis. Accusantium magnam atque incidunt.', '2021-02-27 02:56:44', '2023-02-21 07:25:31');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (21, 1, 'Similique quibusdam libero minima quis ea vero.', 'Accusamus ullam nemo. Repellendus labore officia nemo ea deleniti.
Nostrum odio adipisci voluptate tempora nemo. Corrupti reiciendis aspernatur iste nobis quae hic.', '2024-04-21 13:30:28', '2024-05-01 00:03:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (21, 2, 'Tenetur facilis doloribus exercitationem tempore ipsa.', 'Velit repellendus ex. Eum at sapiente explicabo inventore. Quia rem iusto autem neque natus. Iusto dolorem repellat omnis corporis recusandae.', '2024-02-24 02:35:16', '2024-09-25 23:59:41');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (21, 3, 'Natus magni maxime temporibus porro saepe.', 'Sint itaque earum dolore eveniet vel. Possimus eligendi rem temporibus dicta voluptatibus laboriosam. Delectus accusamus quam iure et hic. Minima quas perspiciatis veniam.', '2023-02-16 13:05:02', '2023-11-30 08:14:56');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (22, 1, 'Maiores explicabo consequatur vitae itaque ab minus est suscipit eius deleniti.', 'Magni unde quas animi vel laborum ipsum. Ducimus ullam repudiandae aliquam error eum incidunt occaecati.', '2022-08-17 15:25:34', '2023-01-31 22:40:57');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (22, 2, 'Sunt dignissimos tempora eos id eius repellat alias corporis dolorum.', 'Impedit quia mollitia ipsum dolore. Labore deleniti consectetur quia. Dolores ut ducimus nesciunt.
Commodi a dolorum. Id harum iusto dolorem.', '2025-04-21 18:43:35', '2025-04-24 14:10:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (22, 3, 'Quae doloribus quam fugiat aspernatur.', 'Quos nam unde dolores officia a saepe. Ab perspiciatis debitis id.
Culpa soluta nesciunt fuga rerum. Molestias voluptas quo nulla nam officiis officia. Sed debitis ipsam optio nisi minus.', '2021-01-05 12:24:40', '2024-04-22 07:53:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (23, 1, 'Nam quam amet quidem reprehenderit harum vel dolore dolores ratione.', 'Labore rerum blanditiis molestias deserunt. Voluptate ullam perferendis explicabo velit maiores. Modi commodi doloremque incidunt mollitia aperiam facere.', '2024-09-14 14:22:41', '2024-09-20 02:05:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (23, 2, 'Natus doloribus ducimus a qui enim.', 'Cupiditate praesentium facere doloremque perspiciatis nulla. Voluptatum cupiditate architecto omnis modi quis soluta.', '2020-07-01 02:57:43', '2023-05-20 13:00:37');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (23, 3, 'Veniam tempore autem ipsum hic commodi repellendus.', 'Deserunt et ipsum facere quis in quibusdam. Tempora temporibus eum veritatis. Atque praesentium quasi dolores molestiae eligendi.', '2024-07-09 20:23:28', '2025-02-07 11:04:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (24, 1, 'Commodi rem porro animi labore maiores incidunt repellat quibusdam odio.', 'Sunt nihil velit provident officia minima. Soluta ratione ut facilis.
Ex at fugiat magni. Quis non numquam totam culpa.', '2024-01-25 11:28:38', '2025-01-13 09:30:16');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (24, 2, 'Id amet distinctio asperiores omnis tenetur.', 'Quos minus officiis asperiores. Pariatur consequuntur sint consectetur rerum ducimus quae. Quidem qui sapiente.', '2020-07-16 18:32:39', '2022-09-11 06:32:45');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (25, 1, 'Porro omnis repellendus quos inventore placeat dolore voluptates placeat.', 'Dolorem nihil voluptas adipisci quam assumenda.
Cum velit porro in. Dolor dolores aperiam consectetur aliquid ipsa reprehenderit.', '2020-12-10 08:39:19', '2024-12-11 19:09:47');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (25, 2, 'Rerum mollitia in asperiores exercitationem repellendus iure placeat non quo similique.', 'Aspernatur assumenda nisi sed consectetur fuga. Dicta omnis repudiandae veniam veniam excepturi. Pariatur adipisci modi quia.
Necessitatibus labore totam perferendis accusantium laudantium.', '2020-07-02 03:18:21', '2022-07-03 20:24:50');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (26, 1, 'Reprehenderit natus et tenetur vel voluptatem tempora eos quam consequatur.', 'Aperiam minus asperiores debitis inventore optio. Necessitatibus laboriosam minima quos ut nam.
Cupiditate quos quia. Nobis sit quam recusandae laudantium aliquid maxime.', '2022-11-06 17:09:58', '2023-11-26 02:45:45');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (26, 2, 'Sequi consequatur ipsa dolorem minima corrupti mollitia.', 'Facilis suscipit quia. Ea cupiditate sequi sit. Esse soluta libero maxime sit accusamus.
Omnis laborum architecto minima quo quis. Porro voluptas consectetur praesentium voluptatum voluptate.', '2022-08-06 04:19:46', '2023-11-17 19:50:11');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (26, 3, 'Fuga dolorem voluptate ipsa repellendus blanditiis autem veniam quas.', 'Hic ea asperiores repellendus.
Ad sapiente corporis labore molestiae. Quidem rerum repellat at quam incidunt eos. Earum deserunt eligendi porro recusandae tenetur fuga.', '2020-07-21 16:31:11', '2023-02-13 16:34:02');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (26, 4, 'Impedit omnis quibusdam praesentium sunt voluptates itaque.', 'Adipisci nobis necessitatibus natus. Nihil laboriosam dolorum placeat. Dicta reprehenderit quisquam hic quae nam.', '2023-08-02 14:17:36', '2024-09-24 00:23:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (27, 1, 'Qui ab rerum perspiciatis non non consectetur iste quibusdam nulla.', 'Voluptates facilis architecto sequi. Quia accusamus animi non quod commodi rerum.
Dolore consectetur expedita tenetur. Cumque minus tenetur ab. Adipisci hic earum debitis corrupti.', '2023-12-22 07:30:37', '2024-03-21 16:58:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (27, 2, 'Nobis nam nesciunt similique praesentium consequatur nemo iure temporibus laborum.', 'Vero nisi eligendi ipsum beatae illum atque. Ipsum doloremque quo voluptates commodi rem accusamus. Quibusdam veniam odio.', '2025-03-09 23:33:06', '2025-07-01 16:00:43');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (27, 3, 'Fugiat sunt nesciunt ex eos mollitia eum asperiores.', 'Nisi cupiditate asperiores porro cum. Sequi voluptatem quae molestias. Dolore cumque veniam neque fugiat quaerat autem.', '2020-08-29 18:47:23', '2024-11-23 11:18:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (28, 1, 'Occaecati in natus modi quae rem iste suscipit unde dolorum.', 'Velit neque doloribus occaecati libero. Illo molestias iste eligendi possimus dolor sunt.
Quibusdam error numquam natus sed. Aperiam sint quibusdam. Officia ad voluptate beatae nostrum.', '2020-12-12 20:58:32', '2023-10-18 22:00:35');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (28, 2, 'Quibusdam rem voluptate necessitatibus fugit autem quibusdam ab earum amet assumenda.', 'Voluptatem rerum laborum cumque quo. Culpa consectetur repudiandae adipisci quisquam quod.', '2024-08-27 03:13:57', '2025-02-03 17:00:30');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (29, 1, 'Nobis recusandae fugiat adipisci alias quas.', 'Distinctio commodi error. Dolore voluptate nulla temporibus fuga.
Labore quis repudiandae neque neque.', '2023-06-02 21:14:32', '2024-01-17 15:25:34');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (29, 2, 'Perferendis voluptates perspiciatis animi aliquid culpa architecto hic occaecati laboriosam.', 'Esse voluptates soluta veritatis praesentium tenetur. Repellendus delectus odit reiciendis atque dolor.
Voluptatibus repellendus veniam quae. Vero quas ad mollitia eveniet.', '2021-03-28 16:14:06', '2024-09-27 06:12:49');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (29, 3, 'Id perferendis tempora iusto aperiam veniam quasi facere impedit adipisci.', 'Occaecati autem sint officiis. Asperiores nisi nisi necessitatibus voluptate voluptates facere.
Est deleniti vero repudiandae consectetur natus impedit officiis. Asperiores est magnam ea.', '2021-07-09 10:43:59', '2023-10-16 07:03:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (30, 1, 'Saepe ad odit voluptatibus neque eum quos tempora recusandae.', 'Voluptas veniam saepe eveniet eius velit occaecati ratione. Suscipit cum eveniet.
Explicabo nihil nesciunt maiores tenetur molestias. Autem architecto quisquam autem molestiae quaerat.', '2021-07-30 01:01:08', '2024-12-01 22:43:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (30, 2, 'Ducimus aut deserunt deleniti doloremque tempore adipisci occaecati.', 'Dolore voluptatibus amet ea. Non aliquid facilis et nam ex.', '2024-07-25 09:29:01', '2024-12-19 18:11:16');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (30, 3, 'Neque similique velit modi minus maiores laboriosam animi.', 'Quaerat repudiandae dignissimos sunt. At quasi qui qui totam ullam.', '2023-09-16 10:49:22', '2024-03-07 15:26:29');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (31, 1, 'Excepturi possimus autem corrupti exercitationem vitae veniam temporibus expedita at.', 'Suscipit dicta incidunt. Inventore assumenda voluptas sit rem ipsum. Laborum dicta fuga itaque.', '2021-07-03 15:43:48', '2022-09-25 12:36:31');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (31, 2, 'Aut delectus et asperiores quas harum quaerat magni ipsa ab assumenda.', 'Rerum enim delectus unde laborum quam modi. Deleniti maxime mollitia voluptate. Maiores officiis alias occaecati soluta. Non facere nihil repellat fugit alias voluptate ex.', '2022-08-03 08:07:33', '2024-05-26 22:45:16');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (31, 3, 'Culpa facilis expedita ex itaque optio repellat est.', 'Sint quod beatae quasi ratione. Maxime eveniet enim nulla quo laudantium. Nulla nam numquam quae doloremque eum doloribus.
Delectus soluta nostrum itaque. Omnis nostrum maxime aut nam.', '2023-10-24 12:58:29', '2024-09-17 15:28:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (31, 4, 'Optio architecto excepturi accusamus modi deserunt dolor vel.', 'Amet dolorem dolorum fugiat aut. Doloremque illo temporibus enim ex.
Sit dolorum fuga dolorem ea possimus rerum.', '2022-02-19 19:40:11', '2024-06-03 08:03:58');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (32, 1, 'Hic culpa amet tempora facere iure incidunt in.', 'Similique dolore mollitia animi totam. Voluptatum maxime rerum excepturi cumque. Consequatur cum porro libero delectus aliquam. Eaque inventore esse ipsum veritatis ad voluptatibus.', '2021-01-27 09:17:56', '2022-07-20 12:05:44');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (32, 2, 'Sunt ad eius quae eaque sint.', 'Voluptatibus repudiandae officia odio. Sit ad hic omnis. Quas molestias officia assumenda odit perferendis.
Temporibus rerum exercitationem occaecati dolorem.', '2023-08-23 20:07:22', '2025-01-14 12:10:55');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (32, 3, 'Nemo perferendis ullam magnam delectus ipsum pariatur laudantium.', 'Vitae dolore reprehenderit provident error.
Aliquid adipisci accusamus amet nemo. Libero ipsum possimus nostrum.
Repellat corporis soluta eligendi cum.
Repellendus eaque ab.', '2024-12-31 07:14:14', '2025-04-10 09:57:47');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (33, 1, 'Adipisci modi quidem commodi possimus maiores totam.', 'Natus quis officiis dignissimos distinctio iure hic. Ad quis iusto natus.
In eaque laboriosam quia voluptas. Et facere perspiciatis necessitatibus recusandae. A laudantium voluptatem recusandae.', '2020-04-23 18:44:06', '2022-06-04 05:54:37');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (33, 2, 'At porro ullam autem voluptas eius.', 'Quos ipsam neque voluptates enim quam beatae. Molestias reprehenderit animi dolorum exercitationem dolorum. Nostrum alias doloremque.
Deleniti quo iure molestias. Est quod reiciendis sunt qui.', '2024-06-26 13:51:23', '2024-10-28 15:33:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (34, 1, 'Voluptates itaque tenetur magnam est modi quia soluta iure reiciendis.', 'Libero doloribus veniam quisquam omnis. Similique laboriosam soluta autem assumenda quibusdam delectus.', '2023-02-10 07:30:44', '2023-04-08 10:15:56');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (34, 2, 'Corrupti asperiores nihil quibusdam possimus perferendis quaerat officia optio sapiente.', 'Minus velit at quis saepe. Reiciendis quod rem reiciendis.
Aliquam ad officia. Excepturi omnis est explicabo a nobis. Sed non ipsa fugiat quam corrupti magnam.', '2023-03-23 15:59:18', '2024-11-03 06:46:54');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (34, 3, 'Nihil odit praesentium temporibus dicta ipsa illum hic.', 'Recusandae minima vitae rem vel quas sequi quibusdam. Molestias error tenetur vero consequuntur quasi odio.', '2020-06-30 07:31:21', '2025-05-08 10:16:58');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (35, 1, 'Quos quam magnam voluptatem beatae doloribus.', 'Minus iste asperiores maxime ad id nostrum necessitatibus. Facilis consequuntur tempore accusamus non tempore. Enim sit mollitia in quos quis voluptatum.', '2024-08-07 21:48:10', '2025-05-31 07:09:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (35, 2, 'Maxime asperiores possimus assumenda nostrum sint.', 'Ullam fuga doloremque. Ratione consequatur nostrum sunt cupiditate qui doloremque. Architecto quia ratione odit nemo magnam.', '2024-03-14 08:38:10', '2025-01-12 10:36:29');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (35, 3, 'Iure dolorum hic vero eos nihil dolores ad.', 'Minima cum corrupti ab dolorem debitis. Architecto ab quibusdam sunt delectus tenetur. Impedit ipsum ab numquam. Corporis earum a quaerat necessitatibus et.', '2023-10-21 22:54:08', '2024-02-03 21:08:51');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (35, 4, 'Officia nisi voluptatum eveniet minus reprehenderit sed qui fuga debitis in.', 'Quibusdam dolorem hic fuga dolor facilis ex. Neque esse fuga.', '2020-11-06 22:07:17', '2022-04-05 19:10:46');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (35, 5, 'Soluta totam dolore fuga dignissimos at reiciendis alias.', 'Nemo perferendis esse eveniet ipsa. Dolorum eius aliquam.
Quidem repudiandae perspiciatis consequuntur earum voluptatum consequuntur. Nobis quas at esse illo consequatur.', '2022-05-20 18:33:46', '2023-07-28 19:07:56');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (36, 1, 'Consequuntur doloremque dolores iure consequuntur aliquid dolor eligendi.', 'Recusandae vel velit facere iure quam. Molestiae expedita soluta sit asperiores mollitia qui.
Eum fugiat maiores officiis facilis repudiandae tempora repudiandae. Enim earum suscipit qui.', '2024-06-16 12:55:48', '2025-01-24 22:18:37');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (36, 2, 'Nulla odio aliquam quisquam modi incidunt iste consectetur.', 'Dolorem ducimus laborum unde distinctio voluptates. Inventore officiis illo similique. Dolores quis aliquid impedit numquam explicabo.', '2022-01-25 04:03:29', '2024-06-26 12:36:55');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (37, 1, 'Magnam a quisquam quasi quisquam optio laudantium fugiat perferendis.', 'Nemo iure distinctio a fugit animi porro. Rerum cupiditate fuga aliquid. Repellendus cumque rem quisquam ex tenetur minus.
Laborum repellendus quaerat eos dolore aperiam. Est pariatur earum illum.', '2022-09-01 21:13:17', '2024-11-01 12:29:54');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (37, 2, 'Architecto quaerat quae modi praesentium tenetur provident quis repellendus.', 'Explicabo totam amet. Cum harum a quae earum molestiae. Sed harum ducimus iste error ab.
Eligendi minus blanditiis facilis consequuntur. Exercitationem aspernatur non ratione.', '2024-10-24 20:03:21', '2025-04-03 05:57:43');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (37, 3, 'Quibusdam laudantium earum blanditiis eaque corporis.', 'In cumque vel consequuntur ipsum officiis libero. Quod odit odio reiciendis. Velit ex quidem consequatur nobis quaerat quibusdam. Et dignissimos placeat perspiciatis et.', '2024-09-25 07:38:38', '2025-06-20 21:25:38');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (37, 4, 'Harum ducimus cumque totam ex blanditiis.', 'Ullam dolore voluptates inventore velit quam. Vel rerum error excepturi. Reiciendis optio aperiam.
Debitis incidunt nam explicabo consequuntur quas.', '2020-11-14 13:18:29', '2024-06-05 04:36:06');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (37, 5, 'Odio fuga repudiandae minus excepturi excepturi.', 'Quis minus dolorum quidem. Voluptatibus perferendis saepe enim. Voluptatum similique voluptatem nobis debitis necessitatibus architecto.', '2025-03-06 02:01:36', '2025-04-19 23:35:31');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (38, 1, 'Cum id eum aliquam ullam consequatur.', 'Illo molestiae fugiat modi reprehenderit eius dolor eos. Repellat quasi quibusdam quasi rerum sequi.
Molestias velit dolores veritatis mollitia.', '2023-07-27 04:22:05', '2024-07-16 12:12:32');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (38, 2, 'Doloribus unde dolorem illum occaecati perspiciatis vitae modi.', 'Sint ducimus saepe nemo maxime nesciunt. Consequatur eum consectetur reprehenderit dolores facere eveniet. Minus beatae vitae doloremque esse voluptates.', '2024-09-01 19:46:36', '2024-09-11 17:04:38');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (39, 1, 'Sapiente reprehenderit tempore reiciendis qui adipisci culpa.', 'Hic iure in temporibus reiciendis. Sit amet asperiores earum dolores nihil. Adipisci fuga pariatur. Suscipit sapiente aliquid dicta laborum cum.', '2020-01-02 08:43:18', '2022-04-18 09:17:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (39, 2, 'Reiciendis doloremque libero ipsam quo mollitia repellendus.', 'Soluta tempore repudiandae possimus magnam distinctio. Est fugiat quibusdam eaque veritatis.
Quo totam blanditiis harum ea repudiandae vero. Dicta sed dolorem ipsum placeat excepturi at.', '2025-05-18 05:12:52', '2025-05-28 16:19:07');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (39, 3, 'Natus explicabo eveniet cupiditate nobis in.', 'Animi harum veniam vel. Et amet officia optio amet aperiam. Non expedita voluptate expedita voluptatum.', '2020-02-24 15:44:49', '2020-08-06 11:12:57');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (39, 4, 'Tempore quibusdam perferendis aspernatur unde.', 'Ex dolores ipsum maxime dicta ipsum vero vel. Voluptatum nulla odit sequi. Nisi dicta id excepturi perferendis in et itaque.
Culpa consequatur enim. Incidunt velit quidem eos.', '2020-08-29 02:47:52', '2023-09-29 20:36:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (40, 1, 'Ad eligendi sequi blanditiis placeat.', 'Vitae ullam aut beatae consectetur quo. Quas placeat tenetur dolorum.', '2025-04-17 23:53:09', '2025-06-20 02:36:14');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (40, 2, 'A quas nulla incidunt eos officia dolorem tenetur iure vero.', 'Repellat dolorem perferendis veritatis repudiandae voluptate. Dolorum occaecati excepturi occaecati.
Quos soluta unde ipsa sit ipsam sapiente. Hic aperiam quod ex quo.', '2022-07-04 06:36:50', '2022-10-29 10:35:19');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (40, 3, 'Consequatur non a provident sapiente inventore necessitatibus eius a fuga recusandae.', 'Explicabo necessitatibus sapiente esse sunt consequatur. Reprehenderit explicabo autem quia nulla. Dolorem sed quae dignissimos praesentium eaque quam.', '2022-08-05 11:50:49', '2023-11-20 12:05:44');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (40, 4, 'Similique accusamus molestiae molestiae placeat.', 'Nesciunt dolorem molestiae repellendus voluptatum quibusdam eius amet. Nam dicta aliquid ipsum in nobis.', '2020-11-08 23:40:30', '2024-05-31 17:54:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (41, 1, 'Similique est qui optio sint.', 'Animi pariatur quos.
Dolores voluptate deleniti minus laudantium. Quae odit quas in unde ratione doloribus illum. Ipsam quos in voluptatum hic magni. Ipsa quae nihil perspiciatis possimus.', '2023-01-08 05:45:19', '2023-06-11 23:04:11');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (41, 2, 'Suscipit quod dolorem enim provident corrupti quisquam.', 'Repudiandae velit est iure iusto iure. Similique voluptate neque id. Autem soluta sunt doloribus voluptates.', '2024-10-23 18:18:08', '2024-12-18 23:53:41');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (42, 1, 'Ducimus accusantium aliquid ipsam laborum vitae est repellendus.', 'In nostrum sint consectetur. Quas nobis voluptates ea. Magni tempora similique consequuntur vero.', '2025-04-18 00:07:22', '2025-06-13 22:14:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (42, 2, 'Veniam optio nam quisquam suscipit numquam in laboriosam exercitationem accusantium.', 'Ut dolore et recusandae deserunt. Nobis fuga aut ab aspernatur. Dignissimos at quas suscipit voluptatibus voluptatum ipsum ea.
Praesentium odio atque alias. Molestiae autem fuga reiciendis.', '2022-04-06 17:30:20', '2023-02-12 21:50:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (42, 3, 'Quasi modi perferendis veritatis sapiente.', 'Magnam ipsum culpa dicta odio doloribus. Non mollitia ut expedita cupiditate. Laudantium laudantium libero aut quo velit maxime.
Dicta facere maiores praesentium voluptas.', '2024-10-20 01:53:52', '2025-04-15 17:54:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (42, 4, 'Eos iste eum adipisci praesentium.', 'Distinctio nam ducimus molestiae necessitatibus nobis excepturi.
Nulla quis corrupti sit culpa. Nesciunt ut earum unde sapiente. Pariatur commodi maiores delectus.', '2021-07-16 12:34:41', '2022-03-12 10:28:02');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (42, 5, 'Consectetur distinctio ipsam voluptas id dolorum animi commodi.', 'Expedita distinctio totam aliquam quaerat molestiae unde. Cumque in porro nisi. Animi nesciunt ab fugit quaerat itaque harum.', '2020-07-03 16:37:52', '2025-04-14 18:16:41');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (43, 1, 'Saepe fuga totam quas pariatur.', 'Dolor explicabo libero temporibus magnam voluptas. Nostrum ipsa molestias consectetur distinctio.
Explicabo deserunt esse. Tenetur cumque eos. Architecto labore corporis ipsa amet occaecati facere.', '2025-06-06 20:22:47', '2025-06-28 12:06:07');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (43, 2, 'Suscipit vel officiis qui expedita illum eveniet vitae.', 'Unde atque autem laboriosam natus facilis. Assumenda quidem qui ullam cum debitis. Dicta aperiam assumenda sit.', '2020-08-12 03:59:23', '2022-03-20 03:00:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (44, 1, 'Similique harum velit reiciendis distinctio totam voluptatum cumque eos molestias.', 'Voluptates explicabo illo cum numquam pariatur cum. Provident quidem ab facere dolores accusantium omnis nisi.', '2025-05-13 15:23:54', '2025-05-22 17:00:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (44, 2, 'Temporibus similique dignissimos at et sunt.', 'Ipsam modi minus cumque numquam recusandae id ducimus. Dolor quam distinctio soluta cupiditate ducimus quas officiis.', '2020-02-15 13:03:05', '2024-12-10 11:50:37');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (44, 3, 'Fuga error in harum vitae ut laudantium.', 'Blanditiis qui maiores ad voluptas atque. Odio debitis corrupti. Officiis soluta quam facere sint vitae porro.', '2021-06-26 09:43:02', '2025-05-25 00:29:11');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (44, 4, 'Sapiente unde tenetur aliquam odio inventore quia odio.', 'Eveniet architecto est numquam. Ut facere odit quam quod dolorem nam.
Saepe animi sint odit perspiciatis ex. Dolorum delectus exercitationem veniam qui maiores.', '2023-09-13 23:45:01', '2024-02-07 17:26:30');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (44, 5, 'Molestias libero nostrum cumque aut aliquid quo voluptatibus a vitae.', 'Quo provident hic possimus vel tempora voluptates voluptatibus.
Natus consequuntur repudiandae iure. Fugit distinctio rem iste iste facere recusandae.
Nihil neque cumque.', '2020-06-15 18:33:27', '2025-02-16 04:35:30');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (45, 1, 'Quidem quam commodi facilis adipisci vel corrupti blanditiis tempore.', 'Deserunt at esse magnam perspiciatis modi quo harum. Aliquid velit iste tempore eaque quia. Recusandae blanditiis porro ad aliquam voluptate.', '2022-08-09 22:54:12', '2024-10-13 18:44:02');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (45, 2, 'Eum molestias similique at accusamus repellat quam.', 'Numquam voluptatum incidunt quam praesentium maiores nam. Vero accusantium consequatur corrupti facilis. Nulla magni accusantium.
Praesentium incidunt aperiam porro cum quae culpa.', '2022-08-27 06:40:03', '2024-10-12 11:18:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (45, 3, 'Nemo provident sed velit rem dolores.', 'Itaque natus minus at consequuntur. Aspernatur reiciendis nostrum deserunt cumque exercitationem fugit. At quis dignissimos nostrum.', '2024-02-18 20:48:27', '2024-08-12 04:08:52');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (46, 1, 'Debitis consequatur aliquid veniam perferendis quo.', 'Vitae praesentium quibusdam aperiam ipsum. Ducimus provident ullam delectus.', '2023-06-19 23:50:24', '2023-08-27 17:14:58');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (46, 2, 'Accusamus quisquam harum consequuntur cupiditate dolorem blanditiis autem facilis eius.', 'Quasi ratione non eveniet. Iure quis omnis commodi natus. Tempore consequatur dolorem voluptates amet. Repudiandae sit quibusdam omnis quisquam.', '2021-02-04 13:09:00', '2022-09-10 23:42:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (47, 1, 'Modi error harum quia voluptatibus nemo eos blanditiis.', 'Id atque recusandae earum. Quod molestiae sunt explicabo ab minima nulla possimus. Enim eum quasi iusto laborum. Tempora ab repellat mollitia.', '2020-09-10 05:12:27', '2023-08-25 16:56:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (47, 2, 'Eius quidem explicabo perspiciatis ducimus in magnam nobis.', 'Voluptatum quia unde unde commodi assumenda eligendi. Earum voluptatibus blanditiis provident expedita. Nemo minima atque at.', '2022-09-30 17:50:15', '2023-01-14 11:54:40');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (47, 3, 'Repellat consequuntur laudantium facilis praesentium culpa est qui.', 'A tempora dignissimos quod. Molestiae laudantium animi laudantium optio veniam cumque.
Itaque nesciunt sed sed modi asperiores. Numquam voluptatem labore eius laboriosam harum blanditiis delectus.', '2021-10-23 19:35:24', '2024-10-03 06:18:52');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (47, 4, 'Aperiam et dolores laborum quia eligendi perferendis veritatis sed quae amet.', 'Numquam deleniti modi. Laudantium voluptatum at illum recusandae. Quae quae officiis esse alias nam.', '2025-06-20 13:29:00', '2025-07-07 16:41:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (47, 5, 'Vitae quod maxime repellendus dolorum voluptatum sequi temporibus quibusdam qui et.', 'Tenetur ratione quae nemo sit voluptatum quasi. Labore aliquam explicabo ullam ea.
Fugit et ut voluptatibus omnis. Eveniet totam recusandae. Molestiae debitis vero reprehenderit.', '2022-05-20 08:00:28', '2025-05-13 02:05:11');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (48, 1, 'Rerum deleniti dolorum impedit ipsum incidunt nam.', 'Iusto non ipsam sint. Nisi natus quos possimus esse. Numquam repudiandae impedit natus veniam.', '2022-05-25 05:53:35', '2024-12-06 12:36:03');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (48, 2, 'Voluptatem expedita similique enim laborum inventore.', 'Officia aperiam repellat dolores eveniet. Distinctio accusantium itaque repellat. Eveniet quis soluta nesciunt ea molestias quo.', '2022-02-13 08:44:41', '2022-05-11 10:00:05');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (49, 1, 'Non nihil reprehenderit molestias dolores praesentium.', 'Magni quaerat aliquam animi. Quisquam iure voluptates.
Magnam repellat molestias hic. Blanditiis cumque harum voluptatem.', '2021-12-26 04:59:47', '2022-09-12 14:07:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (49, 2, 'Veritatis reprehenderit quod deleniti occaecati.', 'Et quis cum delectus odio officiis. Inventore magnam molestiae illo blanditiis adipisci. Fugit voluptas quisquam veniam tempora dolor.', '2025-04-24 17:26:53', '2025-05-20 04:15:07');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (49, 3, 'Voluptates eveniet inventore quos non architecto.', 'Dolores quisquam quod soluta esse. Suscipit corporis autem sint repellat dicta dignissimos.', '2022-10-12 00:19:03', '2023-06-20 21:50:16');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (50, 1, 'Sit voluptatibus dolorum recusandae occaecati dolore.', 'Necessitatibus quibusdam sit. Reprehenderit odit rerum sunt quo. Iusto perspiciatis tempore tenetur quas soluta inventore distinctio.', '2023-10-15 10:11:26', '2024-07-03 07:35:29');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (50, 2, 'Doloremque deleniti incidunt harum nisi quos veritatis dolor culpa illum.', 'Eos ducimus laudantium vero debitis soluta aut.
Ad architecto quo. Perferendis occaecati incidunt provident itaque.
Delectus omnis in sit. Repellat esse quas quos soluta quae. Rem non dolorum.', '2023-03-09 16:27:17', '2024-07-03 12:44:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (51, 1, 'Itaque quidem nihil placeat iusto doloremque corrupti.', 'Mollitia expedita inventore nesciunt necessitatibus nemo velit. Excepturi modi explicabo molestiae illo. Necessitatibus commodi error veniam.', '2022-02-03 05:10:03', '2022-03-19 00:50:29');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (51, 2, 'Non ipsam iusto quasi ut eaque explicabo dolorum earum.', 'Assumenda praesentium omnis corrupti laborum corrupti. Incidunt sed dolore doloribus ullam earum. Odit pariatur illum. Architecto expedita veniam porro officia blanditiis occaecati.', '2024-06-07 06:15:00', '2024-06-27 04:49:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (52, 1, 'Quidem eaque vero pariatur quis pariatur perspiciatis et.', 'Id tenetur consequatur eius eum ipsa porro.
Rem repellendus et accusamus voluptate. Nam veniam numquam. Reprehenderit quasi vel laborum praesentium.', '2023-07-18 21:08:35', '2025-02-28 17:25:06');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (52, 2, 'Illum sapiente molestiae quia in maxime architecto.', 'Accusantium exercitationem iste illum id. Dicta rem impedit nostrum dolore laboriosam. Sequi iure aut iure. Enim eum neque voluptatum ab laboriosam nemo sit.', '2024-11-17 13:22:39', '2024-11-22 00:36:44');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (52, 3, 'Non quaerat ratione eum quasi.', 'Eaque eos repudiandae id vel. Libero laborum accusantium sapiente perspiciatis natus. Accusantium dicta animi repellat eum delectus facere.', '2024-12-15 09:50:16', '2024-12-30 23:13:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (53, 1, 'Aliquam sequi corporis magni cupiditate fugit minus fugiat.', 'Non temporibus quo culpa nisi debitis blanditiis. Labore illum porro magni.
Iure quae commodi at. Eum quasi dicta sit dolores.
Quod eaque harum.
Aliquid officia fuga ea.', '2022-02-03 23:09:36', '2025-05-11 01:47:45');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (53, 2, 'Illum fugit dolore reiciendis nostrum dolorem dicta aperiam optio.', 'Molestiae repellendus laborum quis sed. Ipsum optio iusto non expedita.', '2024-10-13 00:32:12', '2025-03-20 07:16:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (53, 3, 'Odio corporis molestiae illo beatae optio reiciendis.', 'Repudiandae consectetur dolores delectus reiciendis debitis. Tempore quae nostrum quo. Eaque quos voluptate.', '2020-02-17 05:07:32', '2022-06-03 12:39:11');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (53, 4, 'Facere numquam ad laborum ex consectetur asperiores porro cupiditate.', 'Architecto quisquam nemo. Perferendis accusamus aspernatur et aliquam officiis libero.', '2021-01-28 11:16:43', '2023-08-05 08:12:36');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (54, 1, 'Maiores fugit culpa repellat dolor delectus sapiente.', 'Quis voluptas at distinctio provident explicabo. Earum velit perferendis repudiandae veritatis odio.', '2023-01-07 15:01:06', '2024-10-01 11:13:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (54, 2, 'Consequatur delectus nesciunt voluptatibus.', 'Consequatur repellendus maxime blanditiis sint pariatur. Iusto id sint cumque explicabo repellendus. Eos odio laboriosam voluptate eum provident.', '2021-12-08 09:00:45', '2023-08-28 19:05:51');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (54, 3, 'Labore vero quidem magni similique.', 'Ad amet numquam ipsam.
Quidem omnis cum placeat. Vitae incidunt placeat rem veritatis in voluptatum. Veniam eaque eos deserunt officiis ab iste.', '2022-06-03 13:25:58', '2023-07-20 09:29:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (54, 4, 'Distinctio architecto ab blanditiis ad.', 'Laudantium delectus perferendis maiores. Quia quia quae nihil itaque in culpa.
Quasi explicabo perspiciatis itaque odit. Consectetur laudantium neque beatae.', '2024-09-11 03:34:14', '2025-05-22 13:05:46');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (54, 5, 'Voluptate dolore delectus totam dicta optio suscipit.', 'Rem nesciunt ab numquam quasi fuga. Quam qui debitis consequuntur.
Odit ratione minus at non. Accusantium placeat necessitatibus vero delectus.', '2021-05-30 01:21:07', '2023-09-01 01:44:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (55, 1, 'Necessitatibus occaecati illum nobis maxime.', 'Inventore harum dolorum quibusdam. Atque architecto quia unde sed maxime. Aperiam veniam commodi reprehenderit omnis.
Iusto voluptas voluptatum quas. Quae minima veniam doloremque consectetur ipsum.', '2022-09-03 14:38:30', '2023-04-13 18:39:36');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (55, 2, 'Animi esse mollitia sapiente porro.', 'Earum deleniti nemo magnam. Dignissimos molestias distinctio error eos. Ex qui id hic quidem quo.', '2021-11-18 15:49:49', '2024-06-25 11:34:29');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (55, 3, 'Dolor repellendus eligendi voluptatibus optio quibusdam.', 'Asperiores dolorem deserunt voluptas illo velit. Quae tenetur dolorem odio incidunt deserunt. Vitae animi optio vero tenetur. In reiciendis beatae nihil ad dolores.', '2020-04-03 23:43:07', '2022-11-22 14:06:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (55, 4, 'Maiores totam quisquam doloribus nostrum qui.', 'Maiores iste perspiciatis. Numquam corporis quasi. Voluptas itaque a ab. Placeat saepe alias fuga ipsum.', '2020-11-07 04:23:31', '2021-02-03 03:52:50');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (55, 5, 'Vel similique aliquam asperiores eius molestias odio maxime.', 'Sint dignissimos animi quos totam. Ipsam alias dolorem perferendis non adipisci temporibus.', '2020-04-08 11:05:06', '2022-08-02 09:17:05');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (56, 1, 'Quo placeat eum minima laudantium voluptatem.', 'Amet tenetur aut vero consectetur ullam. Delectus sint voluptatibus maiores occaecati laboriosam quasi.', '2021-01-02 22:08:11', '2023-06-16 01:24:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (56, 2, 'Nisi fuga neque debitis odit et adipisci reiciendis alias eveniet quis.', 'Quos vero atque nesciunt. Aut velit consequatur ab molestias totam. Corporis animi aliquam autem sit. Necessitatibus veritatis officiis eos occaecati.', '2024-05-10 16:11:40', '2025-05-10 02:36:09');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (56, 3, 'Autem expedita odit laudantium doloribus esse molestiae qui reprehenderit.', 'Ea deleniti harum delectus quo. Maxime eaque accusantium sapiente.
Veritatis voluptatibus eaque velit optio recusandae. Ducimus eum distinctio at. Esse sequi quia eius.', '2023-12-12 23:34:39', '2023-12-25 10:59:22');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (56, 4, 'Doloribus ab iure in odio voluptate explicabo perspiciatis atque.', 'Aspernatur cum recusandae. Corrupti harum temporibus quis quo necessitatibus.', '2020-03-31 06:40:09', '2024-02-08 02:30:57');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (57, 1, 'Quia facilis iure repudiandae similique molestias dignissimos consectetur rerum.', 'Laborum sapiente explicabo quia.
Aut earum qui saepe.', '2024-11-07 10:00:48', '2025-01-16 13:17:14');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (57, 2, 'Labore eaque vel velit dolorem cumque quas voluptate deserunt incidunt.', 'Pariatur facilis officiis iusto sed architecto autem. Fugiat quo fugit ut quo harum.
Unde eaque molestiae hic doloremque ea. Blanditiis voluptatum alias iure hic non consequuntur.', '2021-04-15 11:48:06', '2023-02-04 03:28:42');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (57, 3, 'Hic tenetur illum blanditiis ipsam.', 'Nam aut repellendus reprehenderit iure voluptatibus cupiditate nisi. Eligendi aperiam unde dolor nostrum. Quis odio aspernatur asperiores tempora suscipit asperiores.', '2021-03-07 01:12:25', '2023-02-13 00:30:27');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (58, 1, 'Sequi ducimus ullam nulla autem nam rem ex aspernatur.', 'Atque quaerat ab ut. Et laboriosam veritatis ut assumenda magni harum. Atque tempore ex eaque.
Autem dolore facilis non nobis culpa. Temporibus saepe dolorem officia labore tempore architecto.', '2022-10-28 08:23:13', '2024-07-22 22:57:25');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (58, 2, 'Veniam nihil qui cum temporibus.', 'Optio architecto voluptatem aspernatur quisquam quis. Sint ipsam libero possimus optio.', '2020-01-20 15:06:24', '2021-05-28 15:48:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (58, 3, 'Expedita reprehenderit ut aliquam nam quo illum.', 'Ducimus rerum hic voluptatem aliquam sunt. Vero reprehenderit ratione ut sit.
Provident asperiores ipsum vero sequi a eum. Porro explicabo eum eum. Cum illo provident dolores minima ut facere.', '2024-05-06 18:07:30', '2024-10-17 15:37:45');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (58, 4, 'Maxime praesentium aut officia iusto dolorum magni.', 'Sed voluptatibus similique id cupiditate. Sapiente ipsam dolorum ex quaerat quo quam.', '2020-10-04 09:28:48', '2023-03-13 21:20:54');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (58, 5, 'Ullam ipsa repellat consequuntur pariatur aliquid natus sequi dicta nesciunt.', 'Harum dolorum dignissimos praesentium a. Voluptatem nisi explicabo sequi occaecati mollitia in. Perferendis ex quisquam.', '2024-12-09 14:55:39', '2025-06-25 08:04:48');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (59, 1, 'Repellat odit quo ut corrupti delectus in.', 'Doloribus eveniet odio autem. Voluptatibus dignissimos saepe dignissimos dignissimos quaerat. Recusandae at eius quo temporibus.', '2023-09-15 04:58:20', '2024-09-24 21:00:55');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (59, 2, 'Totam placeat enim ab reprehenderit consequatur modi impedit autem odit.', 'Ullam tempora non reprehenderit voluptates. Ea facere modi.
Debitis saepe repudiandae. Ipsum magnam laborum debitis laboriosam repellat non.', '2021-08-09 11:45:29', '2024-07-08 11:53:10');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (59, 3, 'Perferendis ipsum nostrum molestias alias ea quo.', 'Dolore iusto cum impedit eum totam. Tempore architecto at quam placeat at similique explicabo.', '2021-03-02 19:40:16', '2022-02-16 06:42:39');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (59, 4, 'Rem sit sed cumque adipisci provident cumque ducimus dolorum beatae.', 'Tempore repellendus libero qui. A mollitia libero laboriosam quidem magni. Vero dicta molestias distinctio deserunt.', '2022-01-21 21:59:35', '2024-01-14 21:16:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (60, 1, 'Quaerat similique sunt corrupti tempora expedita suscipit amet.', 'Harum laborum distinctio nam sint vel inventore. Voluptatem dignissimos deserunt debitis.
Odio optio occaecati blanditiis magnam. Et enim atque consequuntur necessitatibus eveniet.', '2023-12-19 23:08:57', '2024-06-16 11:41:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (60, 2, 'Accusamus fugiat neque voluptas quos nihil.', 'Voluptatibus similique maiores rerum eveniet consequuntur. Nam architecto iure eveniet fuga molestias nulla. Voluptatum maiores adipisci nisi.', '2024-09-20 17:46:10', '2025-04-08 05:39:44');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (60, 3, 'Quod tempora a temporibus laboriosam quia.', 'Autem iure dolor beatae quam nam assumenda. Doloribus similique sed hic totam in.
Exercitationem consequuntur doloribus quas assumenda quae sunt repellat.', '2021-12-18 14:20:28', '2023-10-14 12:12:46');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (60, 4, 'Dolorum dolores illo natus eligendi.', 'Necessitatibus reprehenderit atque inventore deserunt. Quas ea ea aliquid. Quaerat et necessitatibus quae facere reiciendis iste.', '2023-09-06 07:09:41', '2024-08-26 22:44:00');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (61, 1, 'Corporis libero corrupti dolores.', 'Dolore occaecati a nisi. Nostrum hic laborum suscipit velit voluptas assumenda.
In nesciunt ea unde qui. Impedit perspiciatis ducimus aperiam.', '2020-05-23 19:25:26', '2021-09-03 13:39:03');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (61, 2, 'Facilis natus odio eveniet quos cum repellendus.', 'Perspiciatis laborum cum mollitia. Enim accusantium similique velit quod officiis accusantium.', '2020-01-18 13:46:20', '2025-02-13 08:23:12');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (61, 3, 'Repudiandae eius et aperiam consequuntur vero id excepturi odit.', 'Minus eius corporis reprehenderit quos.
Delectus natus harum reprehenderit animi minus. Iusto amet repellendus dicta nihil. Rerum voluptatibus totam sint animi fugit modi.', '2022-03-15 21:58:46', '2022-12-16 07:52:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (61, 4, 'Delectus laborum doloremque id necessitatibus.', 'Dignissimos sequi laboriosam possimus placeat. Consequuntur nihil harum blanditiis dolorem placeat. Odio at earum animi ratione quae accusamus.', '2023-07-21 07:28:41', '2025-06-28 01:17:06');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (62, 1, 'Explicabo nostrum harum magnam nesciunt enim.', 'Ea deleniti nobis laudantium. Similique aut quae.
Quis perspiciatis delectus eveniet ratione. Quaerat illum sapiente inventore. Eligendi animi iusto vitae quibusdam nulla.', '2021-10-22 11:05:30', '2023-07-27 20:45:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (62, 2, 'Quia quos quidem earum veniam.', 'Officia modi enim rerum. Est libero est repudiandae magni tenetur.
Distinctio eum vel nam iste quaerat.
Omnis praesentium veniam cupiditate. Aspernatur eos quo dolore. Blanditiis autem ipsa repellat.', '2023-05-10 23:00:05', '2023-10-10 03:37:23');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (62, 3, 'Omnis eligendi accusamus quaerat saepe dignissimos dicta facere molestias necessitatibus.', 'Architecto porro quisquam tenetur officiis fugit numquam aperiam. Suscipit nulla temporibus autem sint repellendus.
Magni quam esse sit eos officia. Ducimus provident aperiam.', '2021-08-15 04:54:18', '2022-04-16 02:21:37');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (62, 4, 'Soluta minima velit tenetur totam iste illum illum.', 'Ullam quidem tempore repudiandae. Eaque enim earum enim. Necessitatibus ratione vero deleniti id consequatur optio ea.', '2021-03-30 03:42:52', '2021-10-05 11:16:51');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (63, 1, 'Fugit voluptatem vero veniam recusandae enim repudiandae deleniti ex et.', 'Sequi fugiat quidem reprehenderit. Aliquam dolorem explicabo delectus.
Vero repudiandae dolor iste cum. Blanditiis at quisquam asperiores nostrum.', '2022-08-19 08:41:34', '2025-04-28 03:14:51');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (63, 2, 'Inventore distinctio sed facere eligendi vel.', 'Maiores odio est illo repellendus suscipit. Incidunt excepturi voluptatem libero nesciunt doloribus. Consequuntur sint illo odit. Ipsa beatae odit culpa natus placeat ad aliquam.', '2020-08-13 15:48:09', '2021-12-17 21:45:17');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (64, 1, 'Ipsum odit ipsa eos voluptate pariatur deserunt numquam perferendis amet nemo.', 'Laborum beatae dicta beatae et.
Culpa voluptate nemo culpa.
Recusandae ipsa eaque hic dolor. Quam possimus aperiam repudiandae.', '2023-12-13 21:37:26', '2024-05-16 22:03:53');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (64, 2, 'Excepturi fugit voluptas ad culpa.', 'Sequi itaque pariatur nisi. Voluptate iste enim ipsam. Tempore ea quisquam aspernatur consequuntur ad atque maiores. Et repellendus recusandae repellat.', '2021-02-05 19:40:00', '2021-05-27 20:43:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (64, 3, 'Consequatur voluptatibus perspiciatis dolores sequi.', 'Sequi facilis occaecati provident odit sint. Quod voluptatem nesciunt natus aperiam consequatur. Nulla sit ratione repudiandae.', '2025-01-07 10:25:58', '2025-07-04 00:52:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (64, 4, 'Earum saepe voluptas deserunt voluptates eaque eius assumenda maiores repellendus.', 'Reprehenderit eum dolor. Eius itaque minima fugit nostrum.
Harum eligendi dolore a. Architecto iusto ipsa recusandae deserunt inventore placeat.', '2024-05-26 20:55:23', '2025-04-22 00:51:19');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (65, 1, 'Culpa saepe et error itaque consequuntur eum in beatae veniam quasi.', 'Enim amet ut esse commodi officia maiores ut. Veritatis voluptate autem atque. Amet illo quis aperiam quis esse ab alias. Repellendus eveniet blanditiis ea officiis.', '2023-09-20 10:13:54', '2024-09-10 14:53:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (65, 2, 'Ipsam ex quibusdam exercitationem vitae accusamus deserunt suscipit culpa.', 'Excepturi ducimus incidunt odio. Tenetur sunt laborum animi iste velit temporibus. Optio ex possimus asperiores atque.', '2024-08-19 23:55:43', '2024-10-04 03:24:54');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (66, 1, 'Exercitationem quo deleniti sit maxime quos a cum doloremque odio.', 'Odit libero ratione quam eveniet quidem. Quas voluptatum culpa excepturi eaque nostrum quam. Laboriosam ipsam ex fuga laudantium aspernatur quibusdam eaque.', '2020-05-22 22:15:38', '2022-08-16 00:22:03');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (66, 2, 'Minus modi ducimus qui molestias laudantium perspiciatis quam aspernatur.', 'In explicabo tempore ex dicta corrupti amet. Vero nobis reprehenderit similique qui accusantium. Voluptatum veritatis aperiam sed.', '2024-03-14 04:01:02', '2025-05-16 07:56:59');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (67, 1, 'Sunt fuga aliquid quam officiis doloremque perferendis nobis facilis.', 'Quo ducimus optio nostrum nisi. Deleniti cumque nisi quo.
Doloribus excepturi dolorem recusandae libero placeat quaerat. Ducimus odit accusamus accusamus voluptate. Facere nam amet consequatur quos.', '2021-01-20 15:54:01', '2024-06-17 20:00:15');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (67, 2, 'Aliquid iste similique delectus voluptatum ad doloribus quam ipsum voluptate.', 'Voluptates velit rerum similique optio. Et animi aut expedita vitae.
Saepe voluptate repellendus vel maxime quam fugiat. Dolorem earum nulla.', '2024-11-16 07:29:01', '2025-05-10 17:43:57');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (67, 3, 'Repudiandae quidem at quod harum ipsum quis dicta quisquam hic inventore.', 'Quam magni delectus vel mollitia neque numquam. A sed enim praesentium voluptatem quisquam. Laboriosam iusto quidem atque at. Enim rerum sequi ex eum aut.', '2022-05-19 20:53:47', '2024-05-25 00:44:51');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (67, 4, 'Enim architecto consectetur ut qui occaecati dignissimos doloribus eveniet.', 'Maiores corporis quaerat.
Illum ullam ad praesentium. Cupiditate corporis id. Tempore maiores cumque consequatur omnis optio aspernatur.', '2021-09-21 23:26:52', '2022-01-14 10:07:44');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (68, 1, 'Culpa quas saepe reprehenderit reiciendis praesentium odio.', 'Ea porro cum nisi id commodi. Pariatur placeat non praesentium eveniet corporis fugit harum.', '2024-08-25 14:53:41', '2025-05-14 04:40:13');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (68, 2, 'Deserunt numquam fuga dolores voluptate alias placeat eligendi adipisci.', 'Qui facilis rerum aspernatur unde. Voluptatum maxime impedit enim quo.
Iste voluptates delectus dicta. Repellendus quam earum sint eligendi. Neque hic vitae facere nulla.', '2024-12-13 23:55:44', '2025-01-02 17:20:06');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (69, 1, 'Corrupti ducimus sunt facilis labore ducimus at alias molestiae velit.', 'Natus velit aperiam facere quisquam. Non perspiciatis ipsum facere excepturi.
Autem rem quas suscipit illum dignissimos facilis.
Vero maxime ut repellendus assumenda. Assumenda earum ducimus vitae.', '2021-05-14 21:26:47', '2024-06-30 18:12:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (69, 2, 'A ad esse voluptatem illum iusto.', 'Corrupti magni natus nemo dolor eaque. Quae atque accusamus reprehenderit vel reprehenderit.
Dignissimos doloribus earum officiis. Ipsa fuga nobis.', '2020-05-08 01:31:41', '2023-12-14 21:21:40');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (69, 3, 'Perspiciatis iste eius maiores eius.', 'Culpa vero vero laborum provident autem. Rem doloremque aliquam autem reprehenderit nulla iure.
Eos modi incidunt totam consectetur veniam laborum adipisci. Minima quo ut quidem.', '2020-08-07 03:50:52', '2025-04-30 12:55:49');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (70, 1, 'Animi sunt doloremque nisi.', 'Ipsum pariatur mollitia vitae nihil similique vitae ipsum. Accusantium ipsum repellat. Molestias quasi earum praesentium nobis quaerat.', '2022-05-22 11:08:26', '2024-09-15 20:34:50');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (70, 2, 'Dolor voluptatibus maxime culpa tempora a ullam.', 'Dicta earum blanditiis autem minima nobis. Enim tempore quis hic. Quo ratione voluptates quam.', '2020-04-18 01:21:01', '2021-02-28 14:35:48');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (70, 3, 'Quam illum asperiores illo optio nesciunt necessitatibus magni quae adipisci voluptate.', 'Quia corporis cum fuga doloremque mollitia nemo. Exercitationem velit dolor cum omnis soluta pariatur. Magnam deserunt expedita quia. Veritatis fugiat nemo odio aperiam.', '2021-09-22 21:50:13', '2024-01-27 06:20:53');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (70, 4, 'Soluta impedit sunt ea cumque ullam similique.', 'Itaque ex facilis in aliquid non. Minus ducimus aspernatur repellendus. Numquam deserunt consequatur repellat ullam voluptatem.', '2020-12-03 00:14:26', '2022-12-24 05:04:53');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (71, 1, 'Harum nulla pariatur nisi quisquam voluptatem dolore omnis.', 'Necessitatibus nisi cumque sunt ducimus voluptates provident quibusdam. Accusantium soluta veniam quod.', '2025-07-08 11:55:03', '2025-07-15 08:24:26');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (71, 2, 'Nobis atque minima soluta voluptas reiciendis saepe.', 'Iure unde dolorum. Itaque facere ut cum saepe quibusdam.
Occaecati harum aut eum similique. Ex quidem magni autem unde ad.', '2023-07-21 09:31:44', '2024-09-22 21:42:51');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (71, 3, 'Praesentium delectus accusamus nisi nostrum excepturi nostrum ex dolor.', 'Temporibus eos in iure. Quisquam vel eligendi quisquam.
Tenetur magni labore tempora praesentium nulla. Similique distinctio sint delectus autem. Iste esse excepturi cum.', '2023-11-23 01:12:28', '2025-06-15 01:23:00');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (72, 1, 'Aliquid in quia iusto maiores dolor.', 'Cupiditate magnam exercitationem eveniet. Nihil doloribus nesciunt saepe. Nihil corporis assumenda quaerat laborum ullam quae nemo.
Voluptatem facere id ipsa. Quod reiciendis optio.', '2023-02-14 14:40:01', '2024-09-21 19:20:00');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (72, 2, 'Voluptates ex ducimus pariatur adipisci illum suscipit placeat quasi.', 'Numquam corporis doloremque perferendis eius ea reprehenderit. Aut explicabo cupiditate ut est optio incidunt.', '2025-05-22 10:55:51', '2025-06-08 19:35:45');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (73, 1, 'Ex mollitia aperiam architecto quidem reprehenderit enim.', 'Vero odit nihil voluptate adipisci nulla. Pariatur tenetur animi.', '2022-02-13 09:54:26', '2024-10-14 13:12:29');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (73, 2, 'Iste provident assumenda iste atque.', 'Error sunt saepe perferendis laboriosam earum. Qui est numquam quod. Provident necessitatibus rerum ad. Amet reprehenderit a ipsum ut fuga.
Aut atque quibusdam. Molestiae incidunt velit.', '2023-02-18 09:20:32', '2024-09-16 11:24:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (74, 1, 'Minima rem sint animi et.', 'Iure nisi assumenda laborum minima. Quod doloremque fugit ex accusantium modi neque.', '2025-03-23 06:47:31', '2025-04-01 13:04:02');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (74, 2, 'Repellendus accusamus vero tempora reprehenderit ipsa provident maiores.', 'Sapiente quae velit et. Quaerat magnam qui quia earum. Voluptatem labore dolor officia quam nesciunt molestiae similique.', '2022-07-11 02:58:36', '2022-09-09 17:41:33');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (75, 1, 'Consequatur rerum molestiae temporibus labore tempora tempore at earum.', 'Architecto exercitationem consequatur quam eligendi nihil eaque.', '2022-01-16 15:40:55', '2023-07-13 15:56:34');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (75, 2, 'Perspiciatis sint fuga velit a culpa quaerat eaque possimus.', 'Ullam amet eius vitae rerum. Suscipit accusantium amet reprehenderit iste cum dolores.', '2023-04-01 04:24:19', '2023-09-13 23:23:48');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (75, 3, 'Similique eius ex autem debitis cumque necessitatibus tempora voluptate similique.', 'Eos assumenda doloremque. In quo dolore accusamus dignissimos aliquid corporis.', '2020-12-12 16:10:41', '2024-01-26 02:57:10');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (76, 1, 'Voluptate unde animi ipsum ipsa ut voluptate.', 'Nobis commodi maxime laboriosam atque odio. Debitis corporis eligendi.
Ab quam in laborum qui officia dicta.', '2022-10-31 03:33:40', '2024-04-18 23:23:32');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (76, 2, 'Officiis fuga quia saepe dolore dolorum.', 'Eum et nobis. Quae atque voluptatum adipisci.
Excepturi fugit repellat consequatur amet porro corrupti nihil. Nobis eum ullam deserunt. Laboriosam reprehenderit odit modi at dicta sequi.', '2020-07-25 19:28:20', '2023-08-26 21:26:38');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (76, 3, 'Provident ut modi incidunt.', 'Corrupti excepturi occaecati tenetur. Saepe ad nemo nam placeat itaque ad aspernatur. Cumque suscipit deleniti consequatur cupiditate a maiores iste.', '2021-05-12 20:41:33', '2023-12-21 14:40:44');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (76, 4, 'Labore in iusto alias voluptatibus saepe fugiat tempore magnam delectus.', 'Voluptas nam inventore praesentium iure hic. Quos consequuntur totam doloribus vel dolores aliquid pariatur.
Dolore officiis blanditiis quia maiores. Voluptate iste rem deleniti.', '2022-02-01 04:45:24', '2022-08-15 09:06:34');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (76, 5, 'Sint dignissimos ratione fugit voluptate provident quia magni.', 'Nemo eaque placeat temporibus ducimus sit tempora. Recusandae quis rem eum. Cupiditate voluptates quasi natus soluta.', '2021-11-14 05:31:38', '2024-12-02 18:32:08');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (77, 1, 'Veritatis consequatur similique repellat vel repudiandae animi aspernatur.', 'Sequi eveniet adipisci nemo ea. Maxime nostrum perspiciatis officiis excepturi.
Dolor hic nulla molestiae. Est neque quia possimus ut blanditiis.', '2023-12-31 23:31:57', '2024-10-18 09:19:20');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (77, 2, 'Nam voluptatem occaecati distinctio aliquid animi.', 'Atque aliquam explicabo non sunt minima error. Eaque repellendus similique molestiae id aliquid.
Velit aliquid eveniet facere ab. Doloremque occaecati sequi porro.', '2024-03-08 03:01:56', '2025-02-19 21:09:53');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (77, 3, 'Maiores nisi voluptatibus nobis dolorum neque.', 'Eos iusto eaque velit molestias aperiam itaque. Cum asperiores praesentium porro quisquam.
Rerum ratione ad fuga. Explicabo dolores odio veritatis. Rerum cum veniam voluptate sapiente.', '2022-04-13 10:17:56', '2024-02-20 00:10:07');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (77, 4, 'Optio quibusdam commodi adipisci explicabo.', 'Odit esse ut quae. Minus earum officiis suscipit modi numquam alias.', '2020-02-27 15:08:35', '2022-04-29 12:50:39');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (78, 1, 'Unde sit id ullam ullam adipisci a a cumque.', 'Ipsa rerum voluptatum dolorum beatae adipisci est. Nobis nostrum ex sit soluta.
Odio voluptate dolores dolores error vitae debitis. Officiis sequi nostrum deleniti ad eveniet facere voluptatem.', '2020-01-12 08:56:51', '2024-03-07 15:59:30');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (78, 2, 'Repudiandae cupiditate ut vel earum vitae necessitatibus odio nisi sit.', 'Reiciendis exercitationem ex quas maiores commodi fugiat. Voluptas praesentium cum ipsum cupiditate saepe. Officia dolores illum autem. Dolores vel voluptatem sed deserunt occaecati.', '2023-11-17 22:14:23', '2025-04-27 11:59:56');
INSERT INTO mission_parts (mission_id, part_order, title, description, created_at, updated_at) VALUES (78, 3, 'Quaerat odit quia