name: Notify Discord on Push

on:
  push:
    branches:
      - main  # 원하는 브랜치명

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit info
        id: vars
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_URL=${{ github.event.head_commit.url }}" >> $GITHUB_ENV

      - name: Send Discord Notification
        run: |
          MESSAGE="✅ 새 push가 발생했습니다!\n커밋 메시지: $COMMIT_MESSAGE\n작성자: $COMMIT_AUTHOR\nURL: $COMMIT_URL"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
